# Dependencies
markdown: kramdown
highlighter:      pygments

plugins:
  - jekyll-paginate
  - jekyll-gist

# Permalinks
permalink: /:title/

# Setup
title:            Chirag Chauhan
tagline:          'Your friendly neighbourhood'
description:      'I write about random things here'
url:              https://github.com/mr1holmes
baseurl:          ""

author:
  name:           'Chirag Chauhan'
  url:            https://github.com/mr1holmes

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/poole/hyde
